import { t } from '../i18n/index'

/**
 * tag map with i18n support
 */
export const TagMap = {
  get html() { return t('tags.html') },
  get body() { return t('tags.body') },
  get div() { return t('tags.div') },
  get span() { return t('tags.span') },
  get p() { return t('tags.p') },
  get a() { return t('tags.a') },
  get address() { return t('tags.address') },
  get area() { return t('tags.area') },
  get article() { return t('tags.article') },
  get audio() { return t('tags.audio') },
  get b() { return t('tags.b') },
  get button() { return t('tags.button') },
  get canvas() { return t('tags.canvas') },
  get code() { return t('tags.code') },
  get col() { return t('tags.col') },
  get colgroup() { return t('tags.colgroup') },
  get datalist() { return t('tags.datalist') },
  get details() { return t('tags.details') },
  get dialog() { return t('tags.dialog') },
  get em() { return t('tags.em') },
  get embed() { return t('tags.embed') },
  get footer() { return t('tags.footer') },
  get form() { return t('tags.form') },
  get frame() { return t('tags.frame') },
  get h1() { return t('tags.h1') },
  get h2() { return t('tags.h2') },
  get h3() { return t('tags.h3') },
  get h4() { return t('tags.h4') },
  get h5() { return t('tags.h5') },
  get h6() { return t('tags.h6') },
  get header() { return t('tags.header') },
  get hr() { return t('tags.hr') },
  get i() { return t('tags.i') },
  get iframe() { return t('tags.iframe') },
  get img() { return t('tags.img') },
  get input() { return t('tags.input') },
  get textarea() { return t('tags.textarea') },
  get label() { return t('tags.label') },
  get li() { return t('tags.li') },
  get main() { return t('tags.main') },
  get mark() { return t('tags.mark') },
  get menu() { return t('tags.menu') },
  get nav() { return t('tags.nav') },
  get ol() { return t('tags.ol') },
  get picture() { return t('tags.picture') },
  get progress() { return t('tags.progress') },
  get select() { return t('tags.select') },
  get summary() { return t('tags.summary') },
  get table() { return t('tags.table') },
  get tr() { return t('tags.tr') },
  get td() { return t('tags.td') },
  get ul() { return t('tags.ul') },
  get video() { return t('tags.video') },
}
/**
 * input type map with i18n support
 */
export const InputTypeMap = {
  get text() { return t('inputTypes.text') },
  get password() { return t('inputTypes.password') },
  get checkbox() { return t('inputTypes.checkbox') },
  get radio() { return t('inputTypes.radio') },
  get submit() { return t('inputTypes.submit') },
  get reset() { return t('inputTypes.reset') },
  get button() { return t('inputTypes.button') },
  get file() { return t('inputTypes.file') },
  get hidden() { return t('inputTypes.hidden') },
  get image() { return t('inputTypes.image') },
  get email() { return t('inputTypes.email') },
  get url() { return t('inputTypes.url') },
  get tel() { return t('inputTypes.tel') },
  get number() { return t('inputTypes.number') },
  get search() { return t('inputTypes.search') },
  get range() { return t('inputTypes.range') },
  get date() { return t('inputTypes.date') },
  get time() { return t('inputTypes.time') },
  get month() { return t('inputTypes.month') },
  get week() { return t('inputTypes.week') },
  get datetime() { return t('inputTypes.datetime') },
  get color() { return t('inputTypes.color') },
}
